### ISSUE TITLE
<class 'usb.core.USBError'>, (110, 'Operation timed out')

### ISSUE THREAD

**Issue by Alanimus** [jludwig75/trainer_tools#8]
Hi, really interested in your project as I am trying to do something similar when I happened across this. 
I put this on a Raspberry Pi Zero and get the following errors (tried running several of the files)

```
Driver available: [<class 'ant.base.driver.SerialDriver'>, <class 'ant.base.driver.USB2Driver'>, <class 'ant.base.driver.USB3Driver'>]
 - Using: <class 'ant.base.driver.USB2Driver'>
<class 'usb.core.USBError'>, (110, 'Operation timed out')
<class 'usb.core.USBError'>, (110, 'Operation timed out')
<class 'usb.core.USBError'>, (110, 'Operation timed out')
```
What is the appropriate way to run this if I just want to test the output with a generic speed/cadence sensor?

I should add I have pyUSB and Ant+ working on this Pi and I did have a similar issue with code I am working on with pyUSB... and ended up having to use .reset(). No idea if that is related to this issue.

**Comment by pringles50g** [comment]
it seems to me that this happens when our raspberry does not receive any ANT + data ... I had something similar recently, when I started the script without HR strap .... so ... **put on a HR strap** :) and then run the script

**Comment by Alanimus** [comment]
I was running the speed + cadence and using Simulant+ to simulate the
device. Does it only work with HR? I will try that as well.

**Comment by jludwig75** [comment]
There is a script for speed + cadence. It just outputs the speed and cadence right now. I tested it with my speed and cadence sensor, but the speed sensor in it is broken, so I could only get cadence. There is no script to do anything with the sensor data, but I can add one. What are you trying to do? I can also try getting data from Sumlant+ for a speed and cadence sensor.

**Comment by jludwig75** [comment]
I tested the script with Simulant+ and it worked for me. I also get these time out errors until the opeant module picks up the device. Once it picks up the device the errors go away. If I turn off the device, I get timeout errors again. I think this is expected behavior when it can't find a device. I used the Bike Speed & Cadence Simulation and ran the SD_0008 Rollover.py script in the simulator.

**Comment by Alanimus** [comment]
Weird, I deleted the folder, reupped to my Pi Zero W, now it works fine. Thanks for testing and confirming.

**Comment by jludwig75** [comment]
That's good to hear, although I don't know what would have changed.
